name: Deploy Issue Diagram

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python plotter.py -o OctoPi-Team -r OctoPi

      - run: mkdir www && mv diagram.png www
      - name: Create index HTML
        run: echo "<img src='./diagram.png'>" >> www/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
