name: Deploy Issue Diagram

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python plotter.py -o OctoPi-Team -r OctoPi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Diagram Artifact
          path: diagram.png

