name: Automatic Deployment
on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Load Repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Build the App
        run: npm ci && npm run build
      - name: Deploy to Cloud Foundry
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api: https://api.cf.eu10-004.hana.ondemand.com
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: sovanta AG TDD (Pay as you go)_hs-mannheim
          cf_space: Octo Pi
          command: push -f manifest.yml
