name: Deploy Issue Diagram

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'pilip-d'
          repository: 'github-issue-plotter'
      - run: cd github-issue-plotter

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python plotter.py -o OctoPi-Team -r OctoPi
      - name: Create index HTML
        run: echo "<img src='./diagram.png'>" >> index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
